// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("mule-runtime-master-env-log-receiver ")
)

const (
	LogsStability = component.StabilityLevelBeta
)
